### ISSUE TITLE
Request_EntityChanged error, Sales Order not updating.

### ISSUE THREAD

**Issue by oliver-sadler** [ethan-sorenson/EditShipToBillTo#1]
We are getting an issue using this on Business Central cloud v15.2.39558.40612.

When sending a PUT request to the /ShippingAddress endpoint, we are getting a Request_EntityChanged error message. We are passing through the IF-Match header with the ETag of the order we want to update. 

This works with the standard Sales_Order endpoint. I have checked and the ETag on the order does match what we're passing through. How can we fix this?

Possibly an update is needed for v15.2 but not sure where to find documentation to sort this issue.

## Our request is: 

URL: `{{baseurl}}/Company('MyCompany')/ShippingAddress('Order','S-000001')`

Raw Body:
```
{
	"ShipToOptions": "Custom Address",
	"ShipToName": "My Company",
	"ShipToAddress": "My Address",
	"ShipToAddress2": "Address 2",
	"ShipToCity": "My City",
	"ShipToCounty": "My County",
	"ShipToPostCode": "My Postcode"
}
```
Headers:
```
Authorization: Basic {redacted}
Content-Type: application/json
IF-Match: W/"JzQ0O3JxWndQVE1objFQRjVCRFA4akloWFR2UkR3S1dqenNHdzh0MjZaOEtyajA9MTswMDsn"
```

## Here is the full response:

```
{
    "error": {
        "code": "Request_EntityChanged",
        "message": "Another user has already changed the record.  CorrelationId:  bf5c6b13-96ee-4fca-af3c-932faf73f0bd."
    }
}
```

Any help would be appreciated.

**Comment by ethan-sorenson** [comment]
@sequelagency, this has now been resolved with the most recent push. It looks like the issue was a trigger on modify that was causing the record to be modified twice and give you this error. Thank you for bringing it to my attention.
